server {
	listen 80;
	server_name site-a.com www.site-a.com;
	# Конфигурация для site-a (например, путь к файлам)
	root /var/www/site-a;
}

server {
	listen 80;
	server_name site-b.com;
	root /var/www/site-b;
}
